resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/warloc/tst2.git
#      branch : main
      username: vadim.merzlikin@gmail.com
      password: dttH!2022
jobs:
  - name: tests
    plan:
      - get: repo
        trigger: true
      - in_parallel:
          limit: 2
          steps:
          - task: run-gradle-build1
            config:
              platform: linux
              image_resource:
                type: registry-image
                source: { repository: gradle, tag: jdk25 } # Uses a specific Gradle image
              inputs:
                - name: repo
              caches:
                - path: $HOME/.gradle/caches/
                - path: $HOME/.gradle/wrapper/
              run:
                path: /bin/sh
                args:
                  - -ce
                  - |
                    cd repo
                    chmod +x gradlew
                    ./gradlew test -i -Dp.count=12 || true
              params:
                MY_SECRET_VAR: ((super-secret-value)) # Map pipeline var to task env var
          - task: run-gradle-build2
            config:
              platform: linux
              image_resource:
                type: registry-image
                source: { repository: gradle, tag: jdk25 } # Uses a specific Gradle image
              inputs:
                - name: repo
              caches:
                - path: $HOME/.gradle/caches/
                - path: $HOME/.gradle/wrapper/
              run:
                path: /bin/sh
                args:
                  - -ce
                  - |
                    cd repo
                    chmod +x gradlew
                    ./gradlew test -i -Dp.count=11 || true
              params:
                MY_SECRET_VAR: ((super-secret-value)) # Map pipeline var to task env var
          - task: run-gradle-build3
            config:
              platform: linux
              image_resource:
                type: registry-image
                source: { repository: gradle, tag: jdk25 } # Uses a specific Gradle image
              inputs:
                - name: repo
              caches:
                - path: $HOME/.gradle/caches/
                - path: $HOME/.gradle/wrapper/
              run:
                path: /bin/sh
                args:
                  - -ce
                  - |
                    cd repo
                    chmod +x gradlew
                    ./gradlew test -i -Dp.count=10 || true
              params:
                MY_SECRET_VAR: ((super-secret-value)) # Map pipeline var to task env var