# pipeline.yml
jobs:
  - name: example-job
    plan:
      - task: use-custom-var
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: busybox}
          run:
            path: sh
            args:
              - -c
              - |
                echo "The secret value is $MY_SECRET_VAR"
          params:
            MY_SECRET_VAR: ((super-secret-value)) # Map pipeline var to task env var
